# Generated by Django 3.2.8 on 2021-10-23 15:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary_range', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('location1', models.CharField(max_length=100, null=True)),
                ('location2', models.CharField(max_length=100, null=True)),
                ('location3', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobHunt.seeker')),
            ],
        ),
    ]
