# Generated by Django 3.2.8 on 2021-10-07 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobHunt', '0002_remove_job_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
